# Name: Muhammad Uzair
# Roll No. L1F18BSCS0311
# Section: G4
# IDS Assignment 2

# Answer 1

In [41]:
import numpy as np

strArray = np.array([["IDS","IS"],["NM","OBC"],["FYP","CC"],["CCN","TOA"]])
print("Array elements:",strArray)
print("Attributes of the array are: ")
shape = strArray.shape
size = strArray.size
dimension = strArray.ndim
itemSize = strArray.itemsize
dataType = strArray.dtype
print("Shape:",shape)
print("Size:",size)
print("Dimension:",dimension)
print("Item Size:",itemSize)
print("Data type:",dataType)

Array elements: [['IDS' 'IS']
 ['NM' 'OBC']
 ['FYP' 'CC']
 ['CCN' 'TOA']]
Attributes of the array are: 
Shape: (4, 2)
Size: 8
Dimension: 2
Item Size: 12
Data type: <U3


# Answer 2

In [44]:
myArr = np.arange(100, 500, 40)
myArr = myArr.reshape(5,2)
print(myArr)

[[100 140]
 [180 220]
 [260 300]
 [340 380]
 [420 460]]


# Answer 3

In [14]:
def secondColumn(myArr):
    return myArr[:,1]

myArr = np.array([[11,22,33],[44,55,66],[77,88,99]])
items = secondColumn(myArr)
print("Items in second column:",items)

Items in second column: [22 55 88]


# Answer 4

In [21]:
def evenRowsOddColumns(myArr):
    return myArr[1::2,0::2]


myArr = np.array([[3 ,6, 9, 12],[15 ,18, 21, 24],[27 ,30, 33, 36],[39 ,42, 45, 48],[51 ,54, 57, 60]])
items = evenRowsOddColumns(myArr)
print("Items at even row and odd columns:",items)

Items at even row and odd columns: [[15 21]
 [39 45]]


# Answer 5

In [26]:
arrOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray = arrOne + arrTwo
print("Result Array:",resultArray)

resultArray = np.power(resultArray, 3)
print("Result array after modifying it by taking cube of all elements:",resultArray)

Result Array: [[20 39 33]
 [25 25 28]]
Result array after modifying it by taking cube of all elements: [[ 8000 59319 35937]
 [15625 15625 21952]]


# Answer 6

In [31]:
print("8X3 integer array:")
myArr = np.arange(10, 34, 1)
myArr = myArr.reshape(8,3)
print (myArr)

print("\nDividing 8X3 array into 4 sub array")
subArr = np.split(myArr, 4) 
print(subArr)

8X3 integer array:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


# Answer 7

In [34]:
def sortingArr(myArr):
    rowSort = myArr[:,myArr[1,:].argsort()]
    print("Sorting array by second row")
    print(rowSort)
    colSort = myArr[myArr[:,1].argsort()]
    print("Sorting array by second column")
    print(colSort)


myArr = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("Original array") 
print (myArr)
sortingArr(myArr)

Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting array by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
Sorting array by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


# Answer 8

In [40]:
def maxAxisZero(myArr):
    result = np.amax(myArr, 0) 
    print("Max from Axis 0",result)

def minAxisOne(myArr):
    result = np.amin(myArr, 1) 
    print("Min from Axis 1",result)

print("Original array")
myArr = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print(myArr)
print("\n",end="")

maxAxisZero(myArr)
minAxisOne(myArr)

Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Max from Axis 0 [82 94 73]
Min from Axis 1 [34 12 53]
